//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberArk.Extensions.Identity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberArk.Extensions.Identity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password process failed..
        /// </summary>
        internal static string ChangePassFailed {
            get {
                return ResourceManager.GetString("ChangePassFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password process finished successfully.
        /// </summary>
        internal static string ChangePassOK {
            get {
                return ResourceManager.GetString("ChangePassOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconcile account was not assigned.
        /// </summary>
        internal static string NoReconcileAccount {
            get {
                return ResourceManager.GetString("NoReconcileAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was rejected because it referenced an entity that does not exist. The error message describes the entity.
        /// </summary>
        internal static string NoSuchEntityException {
            get {
                return ResourceManager.GetString("NoSuchEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was rejected because the provided password did not meet the requirements imposed by the account password policy.
        /// </summary>
        internal static string PasswordPolicyViolationException {
            get {
                return ResourceManager.GetString("PasswordPolicyViolationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconcile password process failed..
        /// </summary>
        internal static string ReconcilePassFailed {
            get {
                return ResourceManager.GetString("ReconcilePassFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconcile password process finished successfully..
        /// </summary>
        internal static string ReconcilePassOK {
            get {
                return ResourceManager.GetString("ReconcilePassOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request processing has failed because of an unknown error, exception or failure.
        /// </summary>
        internal static string ServiceFailureException {
            get {
                return ResourceManager.GetString("ServiceFailureException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not authorized to perform.
        /// </summary>
        internal static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to perform this operation.
        /// </summary>
        internal static string UserNotAuthorizedMessage {
            get {
                return ResourceManager.GetString("UserNotAuthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify password process failed..
        /// </summary>
        internal static string VerifyPassFailed {
            get {
                return ResourceManager.GetString("VerifyPassFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify password process finished successfully.
        /// </summary>
        internal static string VerifyPassOK {
            get {
                return ResourceManager.GetString("VerifyPassOK", resourceCulture);
            }
        }
    }
}
